### ISSUE TITLE
angular cli setup

### ISSUE THREAD

**Issue by ghost** [tycho01/pug-plugin-ng#2]
Hi I'm trying to setup pug with angular cli version 1.0.0-beta.21 but I'm getting:

> src/app/app.component.pug Unexpected token (1:3) You may need an appropriate loader to handle this file type.

Steps I followed:

1. Create basic angular cli app
2. install pug "npm i -save-dev pug
3. install pug-ng-html-loader "npm i --save-dev pug-ng-html-loader"
4. install pug-plugin-ng "npm i --save-dev pug-plugin-ng"
5. remove app.component.html
5. create app.component.pug
6. in app.component.ts replace templateUrl: './aa.component.html', with 'template: require('./app.component.pug')'
7. run ng serve

Should I add reference to pug-plugin-ng anywhere else in any of the angular cli files like angular-cli.json?

Maybe small guide would be helpful.

Thanks

**Comment by KiaraGrouwstra** [comment]
I'm gonna try and see if I can get a working example somehow. I must admit so far I hadn't gotten Pug working with `angular-cli`, though I'm aware of how ShadowManu [forked it](https://github.com/angular/angular-cli/pull/2205/files), and though I tried a variant closer to what I was used to [myself](https://github.com/tycho01/angular-cli/commit/5b51cb890a31a7658f7d9403f2741eb499056dd6).

Nevertheless, I'm running in a Windows environment and wasn't able to get it to recognize the `ng` dist in the other directory. I tried with Linux subsystem for Windows, but that ran into its own issues.

In your current example the obvious issue appears to be that you're running the stock version of `angular-cli`, which hasn't actually included any Pug support (as ShadowManu's PR has been ignored for lack of docs or tests).

I wish fixing things through `angular-cli.json` were supported, but as it stands, they do no let you configure their Webpack settings, which I personally see as the first thing they should improve on, though even then I'm not sure if that could in itself take care of webpack loaders not natively installed on their side, so that might've complicated things.

I also tried just making the edits in my globally installed copy of `angular-cli`, but somehow hadn't had luck with it yet. That said, technically if you mimick our adjustments on your globally installed copy, for all I know that should work. Alternatively, you might try to globally install ShadowManu's fork, which allegedly someone else got working as well, though that isn't currently using `pug-plugin-ng` yet by default. That said, that probably wouldn't be the hard part.

**Comment by ghost** [comment]
I thought there was nice and easy way to add this plugin to the original angular-cli. It looks like we will have to wait little bit longer for the official solution. For now I'm using Webstorm which have watcher option that watches for pug files and automatically compiles them to html. I'll keep my eye on the angular-cli pug support.

Thanks for your effort.

**Comment by qtleeq** [comment]
Just out of curiosity, does it matter make a difference that you do 

loader: "pug-html"

instead of

loader: "pug-html-loader"

just curious.

**Comment by KiaraGrouwstra** [comment]
@mbonski: Yeah, I've felt a bit frustrated with my attempts at trying pug with `angular-cli` so far as well, although apparently it's possible. I also hope they'll accept his PR.
@TaylorDennisLee: AFAICT Webpack should recognize both notations.

**Comment by KiaraGrouwstra** [comment]
@mbonski: I got some help on this from @TaylorDennisLee, and got it to work as follows:
```
git clone -b pug-html https://github.com/tycho01/angular-cli.git
# alternative: git clone -b pug https://github.com/zoitravel/angular-cli.git
cd angular-cli
npm link
cd PATH/TO/MY/PROJECT
npm link angular-cli
# in component: templateUrl: './my_pug_file.pug',
ng serve
```

**Comment by MarkPieszak** [comment]
Excellent work here @tycho01 

Got it to work with the latest CLI with this:

```typescript
{ test: /.(pug|jade)$/, loader: 'apply-loader' },
{ test: /.(pug|jade)$/,
  loader: 'pug-loader',
  query: { doctype: 'html', plugins: [require('pug-plugin-ng')] },
},
```

If you use the script I made in this article here: https://medium.com/@MarkPieszak/using-pug-or-jade-templates-with-the-angular-cli-9e37334db5bc
You can just replace `const pug_rule` with the below (in the file you make)

```
const pug_rule = `\n
  { test: /\.(pug|jade)$/, loader: 'apply-loader' },
  { test: /\.(pug|jade)$/,
    loader: 'pug-loader',
    query: { doctype: 'html', plugins: [require('pug-plugin-ng')] },
  },`;
```

@mbonski @TaylorDennisLee

**Comment by MarkPieszak** [comment]
@tycho01 Maybe you'd know of a good way to fix this, but for some reason, `include` still doesn't work inside Pug files with this setup... Tried yesterday for the longest time and it was driving me nuts. If you have any ideas, I'm all ears!

**Comment by KiaraGrouwstra** [comment]
@MarkPieszak: good question -- I haven't tried enough in that area. The loader had a [note](https://github.com/pugjs/pug-loader#includes) on includes, though I'm not sure that was the issue. Could it be it's unaware of the current/base file path in this setup?
