### ISSUE TITLE
Case issue

### ISSUE THREAD

**Issue by ganySA** [tycho01/pug-plugin-ng#4]
Hi

I am using this library with gulp and angular cli, however something seems to be lower-casing all my directives e.g ngStyle becomes ngstyle and ngIf becomes ngif, which is breaking angular2....

my gulp file is as follows:

let path = require('path');
let gulp = require('gulp');
let pug  = require('gulp-pug');

let pugFiles = './src/**/*.pug';

let pug_plugin_ng = require('pug-plugin-ng');
let pug_opts = { doctype: 'html', plugins: [pug_plugin_ng] };
gulp.task('compilePug2', () =>
  gulp.src(pugFiles)
  .pipe(pug(pug_opts))
  .pipe( gulp.dest('./src') )
);

gulp.task('default', ['compilePug2'], () => {
  gulp.watch(pugFiles, ['compilePug2']);
});

**Comment by KiaraGrouwstra** [comment]
One way I'd experienced your issue was when I'd converted html to pug using [html2pug](http://html2pug.com/) or [html2jade](http://www.html2jade.org/), which output all-lowercase element names. Could it be possible that's what happened for you as well? You're saying in your pug the case remains preserved, huh?

If related, I'd consider doing a similar web page to theirs to allow converting to pug in a friendlier manner...

**Comment by ganySA** [comment]
Spot on. This is exactly the issue.

Thanks
